import pandas as pd
from sklearn.preprocessing import LabelEncoder
import joblib
brand_encoder = LabelEncoder()
model_encoder = LabelEncoder()
fuel_encoder = LabelEncoder()
transmission_encoder = LabelEncoder()
owner_encoder = LabelEncoder()
le = LabelEncoder()
df = pd.read_csv("used_car_dataset.csv")
df["Brand"] = brand_encoder.fit_transform(df["Brand"])
df["model"] = model_encoder.fit_transform(df["model"])
df["FuelType"] = fuel_encoder.fit_transform(df["FuelType"])
df["Transmission"] = transmission_encoder.fit_transform(df["Transmission"])
df["Owner"] = owner_encoder.fit_transform(df["Owner"])
joblib.dump(brand_encoder, "brand_encoder.pkl")
joblib.dump(model_encoder, "model_encoder.pkl")
joblib.dump(fuel_encoder, "fuel_encoder.pkl")
joblib.dump(transmission_encoder, "transmission_encoder.pkl")
joblib.dump(owner_encoder, "owner_encoder.pkl")
df["AskPrice"] = df["AskPrice"].str.replace("₹","",regex=False)
df["AskPrice"] = df["AskPrice"].str.replace(",","",regex=False)
df["AskPrice"] = df["AskPrice"].astype(int)
df["kmDriven"] = df["kmDriven"].str.replace(",","",regex=False)
df["kmDriven"] = df["kmDriven"].str.replace(" km","",regex=False)
df["kmDriven"] = df["kmDriven"].astype(float)
df = df.drop(columns=["PostedDate","AdditionInfo"])
for col in ["Brand","model","Transmission","Owner","FuelType"]:
    df[col] = le.fit_transform(df[col])
print("encoding completed")    
df.to_csv("cleaned_used_car_dataset.csv", index=False)
df.dropna(inplace=True)
print(df["AskPrice"].head())
print(df["kmDriven"].head())
print(df.dtypes)
print("preprocessing completed")